---
- name:  Test
  hosts: all
  tasks:
   - name: Gather info on installed packages
     ansible.builtin.package_facts:
        manager: auto
   - name: List installed packages
     ansible.builtin.debug:
        var: ansible_facts['packages'] 
        #var: ansible_facts.packages
