---
- name: Reset the Root password
  hosts: all
  vars_files:
    - root_password.yml
  tasks:
    - name: Root Password Reset Process
      ansible.builtin.user:
        user: root
        state: present
        password: "{{ root_password | password_hash('sha512') }}"

